### ISSUE TITLE
Plugin is not defined

### ISSUE THREAD

**Issue by anorudes** [foxhound87/rfx-stack#10]
Hello, @foxhound87, you created the good boilerplate! Thanks ) 
But I have the error message with text:

```
/home/anoru/git/rfx-stack/node_modules/browser-sync-webpack-plugin/index.js:21
Plugin.prototype.apply = function (compiler) {
^

ReferenceError: Plugin is not defined
```

Can you help me? :)

**Comment by foxhound87** [comment]
Your issue is related to the browser-sync-webpack-plugin so you should post an issue on his repo. But I will deepen the problem tomorrow. In the meantime you can try to run a different version of the package changing it into the package.json.

**Comment by anorudes** [comment]
https://github.com/Va1/browser-sync-webpack-plugin/blob/master/index.js
He renamed "Plugin" to "BrowserSyncPlugin" in last version package.

**Comment by anorudes** [comment]
Problem fixed after change package.json:
"browser-sync-webpack-plugin": "~1.0.1",
to
"browser-sync-webpack-plugin": "~1.0.3",

**Comment by foxhound87** [comment]
Thanks for the pull request!
