### ISSUE TITLE
npm install not working on ubuntu 14.04.4

### ISSUE THREAD

**Issue by reddhouse** [foxhound87/rfx-stack#12]
This is probably a user error, but I'm trying to test out the RFX stack on Digital Ocean, and when I run npm install there are a bazillion warnings, followed by these errors:

npm WARN unmet dependency /root/rfx-stack/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-regenerator requires babel-core@'^6.9.0' but will load
npm WARN unmet dependency /root/rfx-stack/node_modules/babel-core,
npm WARN unmet dependency which is version 6.7.7
npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/opt/node/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint-plugin-react@5.1.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@7.0.0 wants eslint-plugin-react@^4.3.0

Any ideas?

**Comment by reddhouse** [comment]
Managed to get a hold of this if it helps.

[npm-debug-log.txt](https://github.com/foxhound87/rfx-stack/files/315395/npm-debug-log.txt)

**Comment by foxhound87** [comment]
You should use at least npm 3.3.6 with node 5. 
I didn't tested on your version. 
If the error persists, try to fix it running `npm cache clean`.

**Comment by foxhound87** [comment]
Should be fixed now.
https://github.com/foxhound87/rfx-stack/commit/32465247966c18350136a5391fd0d4a3800c0399

**Comment by reddhouse** [comment]
I was able to get the main npm install to work, so your fix worked, but apparently I can't run anything newer than node v4.4.5 on Ubuntu, and this causes various errors for the other npm scripts.

**Comment by foxhound87** [comment]
Consider using NVM https://github.com/creationix/nvm

**Comment by reddhouse** [comment]
Ah, I was looking at node LTS. I used NVM to upgrade to node v6.6.2 and the npm install was successful. Thanks.
