### ISSUE TITLE
Updating Service from another service

### ISSUE THREAD

**Issue by briandpassa** [foxhound87/rfx-stack#14]
This is not so much an issue with this stack, but more like a newbie question about putting things together. 

Let's say I added a new service called 'review' which 'user' can give to each 'post' service. Then I added a property of the 'post' called 'noOfReviews' which is just a computed value of total number of reviews on each post. 

How would you best approach this issue with the current stack? 

I tried to add an after-hook to 'review' service at ./api/hooks/ 
`export function noOfReviews() {
  return (hook, next) => {
    const post = hook.app.service('post');
    id = hook.data.objectid;
    post.patch(id, {
        numberOfReviews: 20,
      })
    return next();
  };
}`

I use 'numberOfReviews: 20' just to see if it fires up

This is the ./api/services/review/hooks.after.js 
`import hooks from 'feathers-hooks';
import { noOfReviews } from '~/src/api/hooks/noOfReviews';

export default {
  all: [
    hooks.remove('_id', '__v'),
  ],
  find: [],
  get: [],
  create: [
    noOfReviews(),
  ],
  update: [],
  patch: [],
  remove: [],
};`
but doesn't seem to fire up after a new 'review' is created.

**Comment by foxhound87** [comment]
Your code seems ok. No errors?

You can try to:
- Add a `console.log()` inside the `noOfReviews()` function.
- Restart the api server when you change code if you forgot.
- `return hook;` instead of `return next();`
- Check if `hook.data.objectid` is populated

lastly you can try return the hook only after the `post.patch()` promise is done like this:

```
return post.patch(id, { numberOfReviews: 20, })
  .then((result) => {
     console.log(result);
     return hook;
  });
```

**Comment by briandpassa** [comment]
Oh I made a stupid mistake. Should have put `const id = hook.data.objectid` instead of `id = hook.data.objectid`. Now everything is fine. 

Thanks!

**Comment by foxhound87** [comment]
good :)
