### ISSUE TITLE
page total doesn't update when adding new items

### ISSUE THREAD

**Issue by ischraub** [foxhound87/rfx-stack#18]
Hi,

when I add several items via "Add Random Item" button the "total" page count doesn't get updated. Only once I click i.e. 'next page', then number updates. Seems like it isn't observed.

It's a small thing, nothing serious/urgent/etc.

Many thanks for your hard work on this project!!

**Comment by foxhound87** [comment]
I used a mobx computed value to keep all in sync: https://github.com/foxhound87/rfx-stack/commit/597066061c86b50f48f26012498e43de5f838aa5
