### ISSUE TITLE
Help with running mongo DB

### ISSUE THREAD

**Issue by 29er** [foxhound87/rfx-stack#2]
Hey I love that you are using mobx with react !
I am new to Mongo so I was just curious if you could elaborate on this:
'Run a local mongodb instance before start the server (port 27017).'

I have mongo installed on my Mac but that is as far as Ive gotten.
What is the recommended approach to doing this ?
Thanks

**Comment by 29er** [comment]
Never mind I figured it out by going here : 
https://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/

**Comment by foxhound87** [comment]
great, let me know if you have any other questions.

**Comment by foxhound87** [comment]
great, let me know if you have any other questions.
