### ISSUE TITLE
Best way to toggle browsersync ?

### ISSUE THREAD

**Issue by 29er** [foxhound87/rfx-stack#3]
Love what your doing so far with this @foxhound87 . so i love brwsersync,  but im just wondering the cleanest way to toggle it , so I can have 2 clients (browsers) seeing the same list, but with separate views. IE, sort of like a 'chat' app.
Sorry im still wrapping my head around some of the code, but wondering if you had any thoughts ?

**Comment by 29er** [comment]
figured it out : )

**Comment by foxhound87** [comment]
glad to hear that you like my stack 👍 
as you saw, removing browsersync is pretty simple, it's just a webpack plugin.
I'm planning to improve the project to give more flexibility and reduce deps.

**Comment by foxhound87** [comment]
Note that browsersync is intended to be used only for the development enviroment.
For what you want to achieve, you need to check out the feathers docs:
http://docs.feathersjs.com/

**Comment by briandpassa** [comment]
curious how you cleanly disabled the plugin. newbie here

**Comment by 29er** [comment]
@briandpassa I just removed the plugin declaration in config.client.dev.js , 

```
  new BrowserSyncPlugin({
    host: Config.browsersync.host,
    port: Config.browsersync.port,
    proxy: ['http://', Config.web.host, ':', Config.web.port].join(''),
  }, { reload: false }),
```
