### ISSUE TITLE
Eslinter on Windows throws absurd errors

### ISSUE THREAD

**Issue by Rhywden** [foxhound87/rfx-stack#32]
Basically, when I clone the repo, I get a boatload of **errors** for every single client-side file.

![image](https://cloud.githubusercontent.com/assets/84586/20409715/ee00a62e-ad1a-11e6-94bb-2d95a015ba58.png)

Those should be "warnings" at the most. Who cares if the *indentation* is 8 spaces instead of 6?

I had to disable the linter to get the app to start.

**Comment by foxhound87** [comment]
apparently it matters to many :)

you don't have to disable the linter,

you can fix it running `eslint --fix`

or just add this to the eslint rules in `.eslintrc`:

`linebreak-style: ["error", "windows"]`
