### ISSUE TITLE
Maybe remove deprecated webpack DedupePlugin

### ISSUE THREAD

**Issue by infernalmaster** [foxhound87/rfx-stack#34]
It's used there:
https://github.com/foxhound87/rfx-stack/blob/master/webpack/config.client.build.js#L62

"DedupePlugin: This plugin was removed from webpack. remove it from configuration."
https://github.com/webpack/webpack/blob/5b2afd0bf742e25f8ed118358aaa7b2228cfb625/lib/optimize/DedupePlugin.js#L10

**Comment by foxhound87** [comment]
Thank you, but I should first update webpack to 2.1.0 beta 27
