### ISSUE TITLE
Strange initial redraw for routes with System.import in Chrome

### ISSUE THREAD

**Issue by infernalmaster** [foxhound87/rfx-stack#36]
To reproduce it:
1. start prod server `yarn run web:prod`
2. go to some route with imported component with System.import
3. reload this Chrome tab
4. You should see page renders 2 times

It looks like browser draws server generated DOM and then, when component is loaded with ajax, react clears root container then draws new DOM. Maybe this is issue of `react-router`, but it's good to know if someone else can produce this.

http://recordit.co/2ur8zsuxnh

Was trying ff and safari and didn't saw that flickering.

Chrome: Version 55.0.2883.75 beta (64-bit)
MacOS: 10.11.6

**Comment by foxhound87** [comment]
I noticed it also on chrome, I still can't find the cause.

**Comment by foxhound87** [comment]
Now I just noticed that some pages has this warning:

`Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting`

This occurs if there is something wrong with the server side rendering, and some code is different from the client and server.

I will fix this and the flickering should go away, 
but It's strange that it doesn't occurs on other browsers except chrome.

**Comment by foxhound87** [comment]
It is related to `System.import` and `react-router`, I'm going to fix it.

**Comment by foxhound87** [comment]
Fixed, Thank you for your support.

**Comment by infernalmaster** [comment]
It's I should thank you, you did awesome job 👏
