### ISSUE TITLE
Current Build broken : ESLint Errors and Unhandled Promise Rejections

### ISSUE THREAD

**Issue by pdfowler** [foxhound87/rfx-stack#42]
Trying to run the stack today, I'm suddenly running into errors starting up the web app.

### Unmet Peer Dependencies & Unknown ESLint rules:

I ran into the following unmet peer dependencies before getting the server to start:

1. webpack@2.2.1
1. eslint@3.15.0

In the case of eslint, the newest airbnb rule set uses a rule introduced in eslint@3.14.0, causing the existing eslint@3.13.1 version throw unknown rule errors.

### environment:

* Commit SHA c562f11f05a7079add8b8b6c1368c827faafb164
* node v6.9.2
* npm v3.10.9

### Repro Steps:

1. Pull latest code
1. Run `npm install`
1. run `npm run api:dev` in one terminal, and `npm run web:dev` in another
1. Observe numerous ESLint errors - fix with `npm install eslint@latest`. Rerun `npm run web:dev`
1. Observe the following error: 
`
route: /
(node:75116) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): [object Object]
(node:75116) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): [object Object]`
1. Throw up arms in despair

**Comment by foxhound87** [comment]
My `yarn.lock` was caching something. 

Now I replicated your issue. Fixing.

Thank You.

**Comment by pdfowler** [comment]
Fix Confirmed. Thanks!

**Comment by foxhound87** [comment]
Thank You for your detailed description! 
Very appreciated.
