### ISSUE TITLE
"Items found" not immediately updated after "+ Add New Item" is clicked.

### ISSUE THREAD

**Issue by briandpassa** [foxhound87/rfx-stack#5]
New item is correctly created and shown when I clicked "+ Add New Item". However, the "Items found" number is not automatically updated immediately.

**Comment by foxhound87** [comment]
Yeah, "Items found" is misleading right now, because it represents the actual items shown on the list. 
I will fix the demo with the real total number from the db.

**Comment by briandpassa** [comment]
great!

**Comment by foxhound87** [comment]
I fixed it, take a look at the commit:  https://github.com/foxhound87/rfx-stack/commit/e9d614906c40c21e17ae7b20c2063daa99328403

I will implement a paginator component for the next time!

**Comment by foxhound87** [comment]
Added pagination: https://github.com/foxhound87/rfx-stack/commit/9ef7a3ef399f2fbaa9206fa6b53346aedae7d8b4

**Comment by foxhound87** [comment]
Added pagination: https://github.com/foxhound87/rfx-stack/commit/9ef7a3ef399f2fbaa9206fa6b53346aedae7d8b4
