### ISSUE TITLE
Migrating to router v4 from v3

### ISSUE THREAD

**Issue by mindaugasnakrosis** [foxhound87/rfx-stack#51]
Hello,

I am migrating my application to v4 react-router but the application localy seems unresponsive.
It keeps loading with no response.

I tried console.log, debug in `/src/web/client.jsx` method of `renderApp()`, but nothing is logged out.

I tried logging in `handleRouter()`

I tried logging in `ssr.js`

I am out of thoughts what could cause this.
Maybe any offers on what I should try, maybe there is lower level where I could log something out.
At the moment I don't even know where to start reproducing the issue.

**Comment by mindaugasnakrosis** [comment]
@foxhound87 any ideas?

**Comment by foxhound87** [comment]
the new version of react-router has some issues with SSR. Stick with v3.

**Comment by foxhound87** [comment]
https://github.com/foxhound87/rfx-stack/issues/40
