### ISSUE TITLE
Invalid checksum warning ?

### ISSUE THREAD

**Issue by 29er** [foxhound87/rfx-stack#6]
Is anyone else seeing this React Warning upon running npm run server:dev ?  

React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) tid="3"><div style="position:fixed;heigh
 (server) tid="3"><div style="button:[object Objec.....

Just curious if other folks have seen this.
anyway, i'll dig into and see if I can fix....

**Comment by foxhound87** [comment]
Yeah, this warning is thrown because there are some differences between the generated html of the server side and the client side, maybe some components don't do well server rendering. It seems to vanish after the build. I didn't find the cause yet.
Let me know if you have suggestions. thanks!

**Comment by foxhound87** [comment]
This warning is thrown in the AppLayout container by AppNav and MobX DevTools.
I will figure it out.

**Comment by foxhound87** [comment]
Fixed the `Invalid checksum warning` and with it the the annoying flickering on the initial page load.
https://github.com/foxhound87/rfx-stack/commit/c54edb964b32c3f9562ed2591131fb5448be9e53
