### ISSUE TITLE
Add 'id' option in order to add update/remove on a POST

### ISSUE THREAD

**Issue by 29er** [foxhound87/rfx-stack#7]
FYI, since you have uuid as your id key, you need to add the 'id' option in server/services/post/config.js in order to add full CRUD on Posts. this will override mongo's default '_id' field.
IE:

```
export default {
  model: 'post',
  namespace: '/post',
  options: {
    id:'uuid',
    paginate: {
      default: 25,
      max: 50,
    },
  },
};
```

**Comment by foxhound87** [comment]
Nice, I will edit this for the next realease! Thanks!

**Comment by foxhound87** [comment]
https://github.com/foxhound87/rfx-stack/commit/1d3c29deddf1f8a0176b46344d6cae8e72eae437
