### ISSUE TITLE
Hot module reloadable stores

### ISSUE THREAD

**Issue by ericjuta** [foxhound87/rfx-stack#9]
I haven't actually run this repo, I'm actually bootstrapping my own but with almost identical code for learning purposes!
I was just curious, upon editing a store class in this repo, are they reloadable allowing to maintain state?

**Comment by foxhound87** [comment]
Not yet, but would be nice to have this feature.

**Comment by ericjuta** [comment]
https://gist.github.com/rej156/4524b59ea77a697fb62a39eada5b9bbe
Got this working for you as a thank you!

**Comment by foxhound87** [comment]
Very nice, thank you. I will implement this.

**Comment by anorudes** [comment]
+1, we need hot reload =)

**Comment by foxhound87** [comment]
We have hot-reloadable MobX stores! Thanks to @rej156 
https://github.com/foxhound87/rfx-stack/commit/c2163ac7b51db729c1f298498c2fe2089d37dcc7
